# Generated by Django 5.1.4 on 2025-04-05 07:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0019_teststep_teststep_result'),
    ]

    operations = [
        migrations.AddField(
            model_name='teststep',
            name='step_coordinates',
            field=models.JSONField(blank=True, null=True),
        ),
    ]
