# Generated by Django 5.1.4 on 2025-04-10 08:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0021_exedownload'),
    ]

    operations = [
        migrations.RenameField(
            model_name='exedownload',
            old_name='user_agent',
            new_name='os_name',
        ),
        migrations.AddField(
            model_name='exedownload',
            name='os_version',
            field=models.TextField(blank=True, null=True),
        ),
    ]
