# Generated by Django 5.1.4 on 2025-04-14 11:39

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0022_rename_user_agent_exedownload_os_name_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='exedownload',
            name='download_uid',
            field=models.CharField(max_length=100, null=True, unique=True),
        ),
        migrations.AlterField(
            model_name='exedownload',
            name='user',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='exe_downloads', to='api.user'),
        ),
    ]
