# Generated by Django 5.1.4 on 2025-04-16 07:56

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0023_exedownload_download_uid_alter_exedownload_user'),
    ]

    operations = [
        migrations.DeleteModel(
            name='EXEDownload',
        ),
    ]
