# Generated by Django 5.1.4 on 2025-04-16 08:16

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0024_delete_exedownload'),
    ]

    operations = [
        migrations.CreateModel(
            name='EXEDownload',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('os_name', models.TextField(blank=True, null=True)),
                ('os_version', models.TextField(blank=True, null=True)),
                ('ip_address', models.GenericIPAddressField(blank=True, null=True)),
                ('download_count', models.PositiveIntegerField(default=1)),
                ('last_downloaded', models.DateTimeField(auto_now=True)),
                ('download_uid', models.CharField(max_length=100, null=True, unique=True)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='exe_downloads', to='api.user')),
            ],
        ),
    ]
