# Generated by Django 5.1.4 on 2025-04-16 08:19

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0025_exedownload'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='exedownload',
            name='user',
        ),
    ]
