# Generated by Django 5.1.4 on 2025-04-16 08:19

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0026_remove_exedownload_user'),
        ('exe_installer', '0006_exedownload_alter_systeminfo_exe_download'),
    ]

    operations = [
        migrations.DeleteModel(
            name='EXEDownload',
        ),
    ]
