# Generated by Django 5.1.4 on 2025-05-14 12:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0028_remove_teststep_step_coordinates_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='projectmember',
            name='invitation',
        ),
        migrations.AddField(
            model_name='teststep',
            name='step_coordinates',
            field=models.JSONField(blank=True, null=True),
        ),
    ]
