# Generated by Django 5.1.4 on 2025-05-14 12:53

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0030_projectmember_invitation'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='projectmember',
            name='invitation',
        ),
    ]
