# Generated by Django 5.1.4 on 2025-05-14 13:14

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0031_remove_projectmember_invitation'),
    ]

    operations = [
        migrations.AddField(
            model_name='projectmember',
            name='invitation',
            field=models.OneToOneField(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='member', to='api.projectinvitation'),
        ),
    ]
