# Generated by Django 5.1.4 on 2025-05-22 03:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0033_githubtoken'),
    ]

    operations = [
        migrations.AddField(
            model_name='githubtoken',
            name='clone_path',
            field=models.TextField(blank=True, null=True),
        ),
    ]
