# Generated by Django 5.1.4 on 2025-04-12 13:15

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0022_rename_user_agent_exedownload_os_name_and_more'),
        ('automation', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='systeminfo',
            name='user',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='api.user'),
        ),
    ]
