# Generated by Django 5.1.4 on 2025-04-14 11:39

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0023_exedownload_download_uid_alter_exedownload_user'),
        ('automation', '0002_alter_systeminfo_user'),
    ]

    operations = [
        migrations.AddField(
            model_name='systeminfo',
            name='exe_download',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='api.exedownload'),
        ),
    ]
