# Generated by Django 5.1.4 on 2025-04-16 07:40

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('automation', '0003_systeminfo_exe_download'),
    ]

    operations = [
        migrations.DeleteModel(
            name='SystemInfo',
        ),
    ]
