# Generated by Django 5.1.4 on 2025-04-16 07:40

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('api', '0023_exedownload_download_uid_alter_exedownload_user'),
    ]

    operations = [
        migrations.CreateModel(
            name='SystemInfo',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('os_name', models.CharField(max_length=100)),
                ('os_version', models.CharField(max_length=200)),
                ('architecture', models.CharField(max_length=100)),
                ('cpu', models.CharField(max_length=200)),
                ('ram', models.IntegerField()),
                ('screen_resolution', models.CharField(max_length=50)),
                ('ip_address', models.GenericIPAddressField()),
                ('mac_address', models.CharField(max_length=50)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('exe_download', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='api.exedownload')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='api.user')),
            ],
            options={
                'unique_together': {('user', 'os_name', 'os_version', 'architecture', 'cpu', 'ram', 'screen_resolution', 'ip_address', 'mac_address')},
            },
        ),
    ]
