# Generated by Django 5.1.4 on 2025-04-16 08:05

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('exe_installer', '0002_exedownload_alter_systeminfo_exe_download'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='systeminfo',
            name='exe_download',
        ),
    ]
