# Generated by Django 5.1.4 on 2025-04-16 08:06

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('exe_installer', '0003_remove_systeminfo_exe_download'),
    ]

    operations = [
        migrations.AddField(
            model_name='systeminfo',
            name='exe_download',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='exe_installer.exedownload'),
        ),
    ]
