# Generated by Django 5.1.4 on 2025-04-16 08:19

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0026_remove_exedownload_user'),
        ('exe_installer', '0005_alter_systeminfo_exe_download_delete_exedownload'),
    ]

    operations = [
        migrations.CreateModel(
            name='EXEDownload',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('os_name', models.TextField(blank=True, null=True)),
                ('os_version', models.TextField(blank=True, null=True)),
                ('ip_address', models.GenericIPAddressField(blank=True, null=True)),
                ('download_count', models.PositiveIntegerField(default=1)),
                ('last_downloaded', models.DateTimeField(auto_now=True)),
                ('download_uid', models.CharField(max_length=100, null=True, unique=True)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='api.user')),
            ],
        ),
        migrations.AlterField(
            model_name='systeminfo',
            name='exe_download',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='exe_installer.exedownload'),
        ),
    ]
