# Generated by Django 5.1.4 on 2025-04-21 11:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('exe_installer', '0006_exedownload_alter_systeminfo_exe_download'),
    ]

    operations = [
        migrations.AlterUniqueTogether(
            name='systeminfo',
            unique_together=set(),
        ),
        migrations.AddField(
            model_name='systeminfo',
            name='system_fingerprint',
            field=models.CharField(default='default_fingerprint', max_length=1000),
        ),
    ]
