# Generated by Django 5.1.4 on 2025-04-21 11:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('exe_installer', '0007_alter_systeminfo_unique_together_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='systeminfo',
            name='system_fingerprint',
            field=models.CharField(max_length=1000),
        ),
    ]
