# Generated by Django 5.1.4 on 2025-04-21 12:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('exe_installer', '0008_alter_systeminfo_system_fingerprint'),
    ]

    operations = [
        migrations.AddField(
            model_name='exedownload',
            name='file_version',
            field=models.CharField(default='TesterAlly_01_002.exe', max_length=100),
        ),
    ]
