# Generated by Django 5.1.4 on 2025-04-21 12:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('exe_installer', '0009_exedownload_file_version'),
    ]

    operations = [
        migrations.AlterField(
            model_name='exedownload',
            name='file_version',
            field=models.CharField(max_length=100, null=True),
        ),
    ]
