# Generated by Django 5.1.4 on 2025-04-25 11:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('exe_installer', '0010_alter_exedownload_file_version'),
    ]

    operations = [
        migrations.AddField(
            model_name='exedownload',
            name='is_update_available',
            field=models.CharField(default='no', max_length=3),
        ),
    ]
