# Generated by Django 5.1.4 on 2025-05-19 12:35

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0032_projectmember_invitation'),
        ('exe_installer', '0012_githubprofile'),
    ]

    operations = [
        migrations.AlterField(
            model_name='githubprofile',
            name='user',
            field=models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to='api.user'),
        ),
    ]
