# Generated by Django 5.1.4 on 2025-05-19 13:35

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('exe_installer', '0013_alter_githubprofile_user'),
    ]

    operations = [
        migrations.DeleteModel(
            name='GitHubProfile',
        ),
    ]
